#!/usr/bin/env python

# Code to take in a Cinema database and make a movie from it.
#
# Developer: Terry Turton, Los Alamos National Laboratory
# Developer: David H. Rogers, Los Alamos National Laboratory
#

import numpy as np
import pandas as pd
import os, sys
import cmovie

# Read in yaml params as dictionary
cmovie.core.hello()
movie_params = cmovie.core.get_params()
#print (movie_params)

# Read in data.csv and sort by column of interest
pathIn = movie_params.get("cdb_path") + movie_params.get("cdb_name") + '/'
csv_filename = pathIn + 'data.csv'

dfCDB = pd.read_csv(csv_filename, sep=',')

# Select only those rows in the data.csv dataframe which match the view requested
myviews = movie_params.get ("views")  #
print ('View Requested:' , myviews)
for x in myviews:
    dfCDB = dfCDB[dfCDB[x]==myviews.get(x)]

control_var = movie_params.get("frame_var")
sys.stdout.write ( 'Control Variable: {}\n'.format(control_var))
dfCDB.sort_values(by=control_var, axis=0, ascending=True, inplace=True, kind='quicksort', na_position='last')

cmovie.core.output_movie( movie_params.get("movie_name"), movie_params.get("frame_rate"), pathIn, dfCDB)
